#!/bin/sh

while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "$line" | sed ':a;N;$!ba;s/\n/ /g' | sed 's/\"quoted_status\": {.*//'  |  sed -e 's/.*e, \"text\": \"\(.*\)\", \"is_quote.*/\1/' | sed 's/\\u.*//' | sed -e 's!http\(s\)\{0,1\}://[^[:space:]]*!!g' #| grep -Po '(?<=(, \"text\": \" )).*(?= \", \"is_quote_status\")'
done < "$1"