#!/bin/sh

# Preprocessing of the tweets
# We clean the tweet text, deleting URL
# We find the language and delete tweets which are not in english or dutch
# We compute the sentiment of the remaining tweets
# We save all important tweets info in a new file
new_file=`basename $1 .json`"_clean.json"
ENG="en"
FR="fr"
NL="nl"
relevant_tweet=false;
while IFS='' read -r line || [[ -n "$line" ]]; do
    TWEET="$(echo "$line" | sed ':a;N;$!ba;s/\n/ /g' | sed 's/\"quoted_status\": {.*//'  |  sed -e 's/.*e, \"text\": \"\(.*\)\", \"is_quote.*/\1/' | sed 's/\\u.*//' | sed -e 's!http\(s\)\{0,1\}://[^[:space:]]*!!g')" #  >> sentiment_tweet.json # curl -d "text=@-" http://text-processing.com/api/sentiment/  
    LANG="$(echo "$line" | sed ':a;N;$!ba;s/\n/ /g' | sed -e 's/.*, \"lang\": \"\(.*\)\", \"created_at\".*/\1/')" 
    #if [ "$LANG" != "$ENG" ] && [ "$LANG" != "$FR" ] && [ "$LANG" != "$NL" ];
    if [ ${#LANG} != 2 ]
        then LANG="$(echo "$line" | sed ':a;N;$!ba;s/\n/ /g' | sed 's/.\", \"lang\":.*\, \"profile_background_tile\"//' | sed -e 's/.*, \"lang\": \"\(.*\)\", \"extended_tweet\".*/\1/')" ;
    fi
    #echo "$LANG" >> test.txt
    if [ "$LANG" = "$ENG" ];
    	then sentiment="$(curl -d "text='${TWEET}'" http://text-processing.com/api/sentiment/ | sed -e 's/.*\"label\": \"\(.*\)\"}.*/\1/')" ; 
    	#echo "test: ${TEST}" ; 
    	relevant_tweet=true;
	fi
	if [ "$LANG" = "$FR" ];
    	then sentiment="$(curl -d "language=french&text='${TWEET}'" http://text-processing.com/api/sentiment/ | sed -e 's/.*\"label\": \"\(.*\)\"}.*/\1/')" ; 
    	relevant_tweet=true;
	fi
	if [ "$LANG" = "$NL" ];
    	then sentiment="$(curl -d "language=dutch&text='${TWEET}'" http://text-processing.com/api/sentiment/ | sed -e 's/.*\"label\": \"\(.*\)\"}.*/\1/')" ;
    	relevant_tweet=true;
	fi

	if [ "$relevant_tweet" = true ]; 
		then location="$(echo "$line" | sed ':a;N;$!ba;s/\n/ /g' | sed -e 's/.*\"Polygon\", \"coordinates\": \(.*\)}, \"country_code\".*/\1/')"; 
        #middle_point =
		date="$(echo "$line" | sed ':a;N;$!ba;s/\n/ /g' |  sed 's/.\"created_at\":.*\, \"contributors_enabled\"//' | sed -e 's/.*\"created_at\": \"\(.*\)\", \"quoted_status_id_str\".*/\1/')";
		if [ ${#date} != 30 ];
			then date="$(echo "$line" | sed ':a;N;$!ba;s/\n/ /g' |  sed 's/.\"created_at\":.*\, \"contributors_enabled\"//' | sed -e 's/.*\"created_at\": \"\(.*\)\", \"filter_level\".*/\1/')";
		fi
		echo -e "{ \"text\":\"${TWEET}\", \"lang\": \"$LANG\", \"sentiment\": \"$sentiment\", \"coordinates\": \"${location}\", \"created_at\": \"$date\" }" >> $new_file  ;
		relevant_tweet=false
	fi

done < "$1"
